name: MSD
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout v1
      uses: actions/checkout@v1
    - name: Run test
      run: make test
      working-directory: msdScript
